### ISSUE TITLE
mmcv version

### ISSUE THREAD

**Issue by ZhHaoH** [bluedream1121/RELF#2]
When I use mmcv=2.0.0 to run the evaluate code，it comes up “ImportError: cannot import name 'constant_init' from 'mmcv.cnn' ”

**Comment by mertkaraoglu** [comment]
A bit late, but for future reference; change the following lines:
1. `model/reresnet_model/models/backbones/base_backbone.py; line: 6`  to `from mmengine.runner import load_checkpoint`
2. `model/reresnet_model/models/backbones/re_resnet.py; line 11` to `from mmengine.model import (constant_init, kaiming_init)`

**Comment by ZhHaoH** [comment]
I've solved the problem, but thanks for the answer!
